src/c/so3_core.c File Reference
so3_core.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>
#include <fftw3.h>
#include "ssht.h"
#include "so3_types.h"
#include "so3_error.h"
#include "so3_sampling.h"
Defines
#define MIN(a, b) ((a < b) ? (a) : (b))
#define MAX(a, b) ((a > b) ? (a) : (b))
Typedefs
typedef void(* inverse_complex_ssht)(complex double *, const complex double *, int, int, int, ssht_dl_method_t, int)
typedef void(* inverse_real_ssht)(double *, const complex double *, int, int, ssht_dl_method_t, int)
typedef void(* forward_complex_ssht)(complex double *, const complex double *, int, int, int, ssht_dl_method_t, int)
typedef void(* forward_real_ssht)(complex double *, const double *, int, int, ssht_dl_method_t, int)
Functions
void so3_core_inverse_via_ssht (complex double *f, const complex double *flmn, const so3_parameters_t *parameters)
void so3_core_forward_via_ssht (complex double *flmn, const complex double *f, const so3_parameters_t *parameters)
void so3_core_inverse_via_ssht_real (double *f, const complex double *flmn, const so3_parameters_t *parameters)
void so3_core_forward_via_ssht_real (complex double *flmn, const double *f, const so3_parameters_t *parameters)
void so3_core_inverse_direct (complex double *f, const complex double *flmn, const so3_parameters_t *parameters)
void so3_core_forward_direct (complex double *flmn, const complex double *f, const so3_parameters_t *parameters)
void so3_core_inverse_direct_real (double *f, const complex double *flmn, const so3_parameters_t *parameters)
void so3_core_forward_direct_real (complex double *flmn, const double *f, const so3_parameters_t *parameters)
Detailed Description
Core algorithms to perform Wigner transform on the rotation group SO(§).
Author:
Martin Büttner
Jason McEwen
Definition in file so3_core.c.
Define Documentation
#define MAX (a, b) ((a > b) ? (a) : (b))
Definition at line 27 of file so3_core.c.
Referenced by get_max_error(), so3_core_forward_direct(), so3_core_forward_via_ssht(), so3_core_forward_via_ssht_real(), so3_core_inverse_direct(), so3_core_inverse_via_ssht(), so3_core_inverse_via_ssht_real(), so3_test_gen_flmn_complex(), and so3_test_gen_flmn_real().
#define MIN (a, b) ((a < b) ? (a) : (b))
Definition at line 26 of file so3_core.c.
Referenced by so3_core_forward_direct(), so3_core_forward_direct_real(), so3_core_inverse_direct(), and so3_core_inverse_direct_real().
Typedef Documentation
typedef void(* forward_complex_ssht)(complex double *, const complex double *, int, int, int, ssht_dl_method_t, int)
Definition at line 31 of file so3_core.c.
typedef void(* forward_real_ssht)(complex double *, const double *, int, int, ssht_dl_method_t, int)
Definition at line 32 of file so3_core.c.
typedef void(* inverse_complex_ssht)(complex double *, const complex double *, int, int, int, ssht_dl_method_t, int)
Definition at line 29 of file so3_core.c.
typedef void(* inverse_real_ssht)(double *, const complex double *, int, int, ssht_dl_method_t, int)
Definition at line 30 of file so3_core.c.
Function Documentation
void so3_core_forward_direct (complex double * flmn, const complex double * f, const so3_parameters_t * parameters)
Compute forward Wigner transform for a complex signal directly (without using SSHT).
Parameters:
[out] flmn Harmonic coefficients. If n_mode is different from SO3_N_MODE_ALL, this array has to be nulled before being passed to the function.
[in] f Function on sphere. Provide a buffer of size (2*L-1)*L*(2*N-1).
[in] parameters A fully populated parameters object. The reality flag is ignored. Use so3_core_forward_via_ssht_real instead for real signals.
Return values:
none
Author:
Martin Büttner
Jason McEwen
Definition at line 1354 of file so3_core.c.
References so3_parameters_t::dl_method, so3_parameters_t::L, so3_parameters_t::L0, MAX, MIN, so3_parameters_t::N, so3_parameters_t::n_mode, so3_parameters_t::sampling_scheme, SO3_ERROR_GENERIC, SO3_ERROR_MEM_ALLOC_CHECK, SO3_N_MODE_ALL, SO3_N_MODE_EVEN, SO3_N_MODE_L, SO3_N_MODE_MAXIMUM, SO3_N_MODE_ODD, SO3_PION2, SO3_PROMPT, so3_sampling_elmn2ind(), so3_sampling_weight(), so3_parameters_t::steerable, so3_parameters_t::storage, and so3_parameters_t::verbosity.
Referenced by main().
void so3_core_forward_direct_real (complex double * flmn, const double * f, const so3_parameters_t * parameters)
Compute forward Wigner transform for a real signal directly (without using SSHT).
Parameters:
[out] flmn Harmonic coefficients. If n_mode is different from SO3_N_MODE_ALL, this array has to be nulled before being past to the function.
[in] f Function on sphere. Provide a buffer of size (2*L-1)*L*(2*N-1).
[in] parameters A fully populated parameters object. The reality flag is ignored. Use so3_core_forward_direct instead for complex signals.
Return values:
none
Author:
Martin Büttner
Jason McEwen
Definition at line 2255 of file so3_core.c.
References so3_parameters_t::dl_method, so3_parameters_t::L, so3_parameters_t::L0, MIN, so3_parameters_t::N, so3_parameters_t::n_mode, so3_parameters_t::sampling_scheme, SO3_ERROR_GENERIC, SO3_ERROR_MEM_ALLOC_CHECK, SO3_N_MODE_ALL, SO3_N_MODE_EVEN, SO3_N_MODE_L, SO3_N_MODE_MAXIMUM, SO3_N_MODE_ODD, SO3_PION2, SO3_PROMPT, so3_sampling_elmn2ind_real(), so3_sampling_weight(), so3_parameters_t::steerable, so3_parameters_t::storage, and so3_parameters_t::verbosity.
Referenced by main().
void so3_core_forward_via_ssht (complex double * flmn, const complex double * f, const so3_parameters_t * parameters)
Compute forward Wigner transform for a complex signal via SSHT.
Parameters:
[out] flmn Harmonic coefficients. If n_mode is different from SO3_N_MODE_ALL, this array has to be nulled before being past to the function.
[in] f Function on sphere. Provide a buffer of size (2*L-1)*L*(2*N-1).
[in] parameters A fully populated parameters object. The reality flag is ignored. Use so3_core_forward_via_ssht_real instead for real signals.
Return values:
none
Author:
Martin Büttner
Jason McEwen
Definition at line 253 of file so3_core.c.
References so3_parameters_t::dl_method, so3_parameters_t::L, so3_parameters_t::L0, MAX, so3_parameters_t::N, so3_parameters_t::n_mode, so3_parameters_t::sampling_scheme, SO3_ERROR_GENERIC, SO3_ERROR_MEM_ALLOC_CHECK, SO3_N_MODE_EVEN, SO3_N_MODE_MAXIMUM, SO3_N_MODE_ODD, SO3_PI, SO3_PROMPT, so3_sampling_elmn2ind(), SO3_SAMPLING_MW, SO3_SAMPLING_MW_SS, SO3_STORAGE_COMPACT, SO3_STORAGE_PADDED, so3_parameters_t::steerable, so3_parameters_t::storage, and so3_parameters_t::verbosity.
Referenced by main().
void so3_core_forward_via_ssht_real (complex double * flmn, const double * f, const so3_parameters_t * parameters)
Compute forward Wigner transform for a real signal via SSHT.
Parameters:
[out] flmn Harmonic coefficients. If n_mode is different from SO3_N_MODE_ALL, this array has to be nulled before being past to the function.
[in] f Function on sphere. Provide a buffer of size (2*L-1)*L*(2*N-1).
[in] parameters A fully populated parameters object. The reality flag is ignored. Use so3_core_forward_via_ssht instead for complex signals.
Return values:
none
Author:
Martin Büttner
Jason McEwen
Definition at line 700 of file so3_core.c.
References so3_parameters_t::dl_method, so3_parameters_t::L, so3_parameters_t::L0, MAX, so3_parameters_t::N, so3_parameters_t::n_mode, so3_parameters_t::sampling_scheme, SO3_ERROR_GENERIC, SO3_ERROR_MEM_ALLOC_CHECK, SO3_N_MODE_EVEN, SO3_N_MODE_MAXIMUM, SO3_N_MODE_ODD, SO3_PI, SO3_PROMPT, so3_sampling_elmn2ind_real(), SO3_SAMPLING_MW, SO3_SAMPLING_MW_SS, SO3_STORAGE_COMPACT, SO3_STORAGE_PADDED, so3_parameters_t::steerable, so3_parameters_t::storage, and so3_parameters_t::verbosity.
Referenced by main().
void so3_core_inverse_direct (complex double * f, const complex double * flmn, const so3_parameters_t * parameters)
Compute inverse Wigner transform for a complex signal directly (without using SSHT).
Parameters:
[out] f Function on sphere. Provide a buffer of size (2*L-1)*L*(2*N-1).
[in] flmn Harmonic coefficients.
[in] parameters A fully populated parameters object. The reality flag is ignored. Use so3_core_inverse_via_ssht_real instead for real signals.
Return values:
none
Author:
Martin Büttner
Jason McEwen
Definition at line 951 of file so3_core.c.
References so3_parameters_t::dl_method, so3_parameters_t::L, so3_parameters_t::L0, MAX, MIN, so3_parameters_t::N, so3_parameters_t::n_mode, so3_parameters_t::sampling_scheme, SO3_ERROR_GENERIC, SO3_ERROR_MEM_ALLOC_CHECK, SO3_N_MODE_ALL, SO3_N_MODE_EVEN, SO3_N_MODE_L, SO3_N_MODE_MAXIMUM, SO3_N_MODE_ODD, SO3_PI, SO3_PION2, SO3_PROMPT, so3_sampling_elmn2ind(), so3_parameters_t::steerable, so3_parameters_t::storage, and so3_parameters_t::verbosity.
Referenced by main().
void so3_core_inverse_direct_real (double * f, const complex double * flmn, const so3_parameters_t * parameters)
Compute inverse Wigner transform for a real signal directly (without using SSHT).
Parameters:
[out] f Function on sphere. Provide a buffer of size (2*L-1)*L*(2*N-1).
[in] flmn Harmonic coefficients for n >= 0. Note that for n = 0, these have to respect the symmetry flm0* = (-1)^(m+n)*fl-m0, and hence fl00 has to be real.
[in] parameters A fully populated parameters object. The reality flag is ignored. Use so3_core_inverse_direct instead for complex signals.
Return values:
none
Author:
Martin Büttner
Jason McEwen
Definition at line 1850 of file so3_core.c.
References so3_parameters_t::dl_method, so3_parameters_t::L, so3_parameters_t::L0, MIN, so3_parameters_t::N, so3_parameters_t::n_mode, so3_parameters_t::sampling_scheme, SO3_ERROR_GENERIC, SO3_ERROR_MEM_ALLOC_CHECK, SO3_N_MODE_ALL, SO3_N_MODE_EVEN, SO3_N_MODE_L, SO3_N_MODE_MAXIMUM, SO3_N_MODE_ODD, SO3_PI, SO3_PION2, SO3_PROMPT, so3_sampling_elmn2ind_real(), so3_parameters_t::steerable, so3_parameters_t::storage, and so3_parameters_t::verbosity.
Referenced by main().
void so3_core_inverse_via_ssht (complex double * f, const complex double * flmn, const so3_parameters_t * parameters)
Compute inverse Wigner transform for a complex signal via SSHT.
Parameters:
[out] f Function on sphere. Provide a buffer of size (2*L-1)*L*(2*N-1).
[in] flmn Harmonic coefficients.
[in] parameters A fully populated parameters object. The reality flag is ignored. Use so3_core_inverse_via_ssht_real instead for real signals.
Return values:
none
Author:
Martin Büttner
Jason McEwen
Definition at line 48 of file so3_core.c.
References so3_parameters_t::dl_method, so3_parameters_t::L, so3_parameters_t::L0, MAX, so3_parameters_t::N, so3_parameters_t::n_mode, so3_parameters_t::sampling_scheme, SO3_ERROR_GENERIC, SO3_ERROR_MEM_ALLOC_CHECK, SO3_N_MODE_EVEN, SO3_N_MODE_MAXIMUM, SO3_N_MODE_ODD, SO3_PI, SO3_PROMPT, so3_sampling_elmn2ind(), SO3_SAMPLING_MW, SO3_SAMPLING_MW_SS, SO3_STORAGE_COMPACT, SO3_STORAGE_PADDED, so3_parameters_t::steerable, so3_parameters_t::storage, and so3_parameters_t::verbosity.
Referenced by main().
void so3_core_inverse_via_ssht_real (double * f, const complex double * flmn, const so3_parameters_t * parameters)
Compute inverse Wigner transform for a real signal via SSHT.
Parameters:
[out] f Function on sphere. Provide a buffer of size (2*L-1)*L*(2*N-1).
[in] flmn Harmonic coefficients for n >= 0. Note that for n = 0, these have to respect the symmetry flm0* = (-1)^(m+n)*fl-m0, and hence fl00 has to be real.
[in] parameters A fully populated parameters object. The reality flag is ignored. Use so3_core_inverse_via_ssht instead for complex signals.
Return values:
none
Author:
Martin Büttner
Jason McEwen
Definition at line 475 of file so3_core.c.
References so3_parameters_t::dl_method, so3_parameters_t::L, so3_parameters_t::L0, MAX, so3_parameters_t::N, so3_parameters_t::n_mode, so3_parameters_t::sampling_scheme, SO3_ERROR_GENERIC, SO3_ERROR_MEM_ALLOC_CHECK, SO3_N_MODE_EVEN, SO3_N_MODE_MAXIMUM, SO3_N_MODE_ODD, SO3_PI, SO3_PROMPT, so3_sampling_elmn2ind_real(), SO3_SAMPLING_MW, SO3_SAMPLING_MW_SS, SO3_STORAGE_COMPACT, SO3_STORAGE_PADDED, so3_parameters_t::steerable, so3_parameters_t::storage, and so3_parameters_t::verbosity.
Referenced by main().